### ISSUE TITLE
[*Collector.py]Replace time.wait with webdriver alternative. 

### ISSUE THREAD

**Issue by giahuydo99** [thebananablender/arbitrage-finder#18]
Here's something I found on some forum: https://stackoverflow.com/questions/12692172/test-dynamically-loaded-content-with-selenium-web-driver

![image](https://user-images.githubusercontent.com/43259657/71939109-8cfd7b80-3201-11ea-91fc-65e1277cd2dd.png)

Could make our programs much more faster. But low priority.

**Comment by thebananablender** [comment]
Been at this one for a few days, it appears with Sportsbet, there'll always need to be some sort of time.sleep() call.. 

This is because even when using an explicit wait to wait for the clicked accordion to fully load before clicking the next one, some accordions will remain unclicked because of the automatic page scrolling throwing off the coordinates of the clicks

Because there is no way to explicitly wait for a page scroll using Selenium, we're forced to call a time.sleep() to wait until the page finishes scrolling. Having said that, using explicit waits HAVE reduced the time.sleep() calls from 1 second to 0.3 seconds

**Comment by thebananablender** [comment]
Time.sleep() calls are needed to make the bot undetectable by websites.. looks like theres no other way around it so closing this
